spring:
  boot:
    admin:
      routes:
        endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream,activiti
      turbine:
        clusters: TURBINE-CLUSTER
        location: monitoring
          
server: 
  port: 1111
  
security:
  user:
    name: admin
    password: ${ADMIN_SERVICE_PASSWORD:DfqCVNZSMjzFUv8Zpk94eftCju59zFWzULjsU1heev4=}
  oauth2:
    client:
      accessTokenUri: http://localhost:5000/uaa/oauth/token
      userAuthorizationUri: http://localhost:5000/uaa/oauth/authorize
      clientId: ticketing-service
      clientSecret: 12345
      authorized-grant-types: authorization_code,refresh_token,password
    resource:
      userInfoUri: http://localhost:5000/uaa/users/current
