logging:
  level:
    org.springframework.security: INFO

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
    RemoteMessageClientCommand:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
    RemoteMessageAnnotationClient:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

eureka: 
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${DISCOVERY_URI:http://localhost:8761/eureka/}

security:
  oauth2:
    resource:
      # user-info-uri: http://auth-service:5000/uaa/users/current
      user-info-uri: http://127.0.0.1:9080/uaa/users/current

management:
  security:
    enabled: false
