version: '2'
services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.0.0
        ports:
            - 9200:9200
            - 9300:9300
        environment:
            ES_JAVA_OPTS: "-Xmx1024m -Xms1024m"
        volumes:
            - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
            - ./elasticsearch/data:/usr/share/elasticsearch/data
        networks:
            - elk
#    logstash_filebeat:
#        image: docker.elastic.co/logstash/logstash:6.0.0
#        ports:
#            - 5000:5000
#        environment:
#            LS_JAVA_OPTS: "-Xmx512m -Xms512m"
#        volumes:
#            - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
#            - ./logstash/pipeline/nginx:/usr/share/logstash/pipeline
#        networks:
#            - elk
#        depends_on:
#            - elasticsearch
#    logstash_metricbeat:
#        image: docker.elastic.co/logstash/logstash:6.0.0
#        ports:
#            - 5001:5001
#        environment:
#            LS_JAVA_OPTS: "-Xmx512m -Xms512m"
#        volumes:
#            - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
#            - ./logstash/pipeline/system:/usr/share/logstash/pipeline
#        networks:
#            - elk
#        depends_on:
#            - elasticsearch
    kibana:
        image: docker.elastic.co/kibana/kibana:6.0.0
        ports:
            - 5601:5601
        volumes:
            - ./kibana/config/:/usr/share/kibana/config
        networks:
            - elk
        depends_on:
            - elasticsearch
networks:
    elk:
        driver: bridge
