spring:
  application:
    name: admin-application
  cloud:
    config:
      password: ${CONFIG_SERVICE_PASSWORD:m34VWxcFy6g8C2/sCAATRMeBsgCmMRvv1whKm/qtXXo=}
      discovery:
        enabled: true
        serviceId: config-server